#!/usr/bin/env bash
if [ $# -le 0 ];
then
    echo "Test case is not set, using default: \"test\""
    testcases=../test
else
    testcases=$1
fi

INITIAL_DIR=$(pwd)
build_dir=""
readonly TEST_BUILD_DIR=${build_dir:-${testcases}/data}


cleanup() {
	# rm -rf would do the job as well, but I hate using rm -rf in a script with
	# variables. Hence, this workaround which is _slightly_ safer
	rm -r "${TEST_BUILD_DIR:?}" 2>/dev/null || true
	mkdir -p "${TEST_BUILD_DIR}"
	sed 's/|->/maps to/g' "$INITIAL_DIR"/StateGraph_Time.dot > AEG.dot
	mv -t "$TEST_BUILD_DIR" "$INITIAL_DIR"/*
	

	rmdir "$INITIAL_DIR"
	
}
trap cleanup EXIT


